# Generated by Django 4.2.7 on 2023-12-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDataStrucutre',
            new_name='TaskDataStructure',
        ),
    ]
