# Generated by Django 4.2.7 on 2024-01-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_alter_datastructure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastructure',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='structure.categorydatestructure'),
        ),
        migrations.AlterField(
            model_name='imagedatastructure',
            name='data_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_to_data_strucutre', to='structure.datastructure'),
        ),
        migrations.AlterField(
            model_name='taskdatastructure',
            name='data_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_task_to_data_structure', to='structure.datastructure'),
        ),
        migrations.AlterField(
            model_name='urldatastructure',
            name='data_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulr_to_online_theory_data_structure', to='structure.datastructure'),
        ),
    ]
