# Generated by Django 4.2.7 on 2024-01-27 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_alter_datastructure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdatastructure',
            name='data_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='structure.datastructure', verbose_name='Структура данных'),
        ),
        migrations.AlterField(
            model_name='imagedatastructure',
            name='data_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_data_structure', to='structure.datastructure'),
        ),
        migrations.AlterField(
            model_name='taskdatastructure',
            name='data_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_to_data_structure', to='structure.datastructure'),
        ),
        migrations.AlterField(
            model_name='urldatastructure',
            name='data_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_to_theory_data_structure', to='structure.datastructure'),
        ),
    ]
