# Generated by Django 4.2.7 on 2023-11-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagealgorithm',
            options={'verbose_name': 'фотография для алгоритма', 'verbose_name_plural': 'Фотографии для алгоритмов'},
        ),
        migrations.AlterModelOptions(
            name='imagecategory',
            options={'verbose_name': 'фотография для категории', 'verbose_name_plural': 'Фотографии для категорий'},
        ),
        migrations.RemoveField(
            model_name='algorithm',
            name='url',
        ),
        migrations.CreateModel(
            name='UrlCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.category')),
            ],
            options={
                'verbose_name': 'ссылка для категории',
                'verbose_name_plural': 'ссылки для категорий',
            },
        ),
        migrations.CreateModel(
            name='UrlAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.algorithm')),
            ],
            options={
                'verbose_name': 'ссылка для алгоритма',
                'verbose_name_plural': 'ссылки для алгоритмов',
            },
        ),
    ]
