# Generated by Django 4.2.7 on 2023-11-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_alter_imagealgorithm_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание задачи')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.algorithm')),
            ],
            options={
                'verbose_name': 'задача для алгоритма',
                'verbose_name_plural': 'задачи для алгоритмов',
            },
        ),
    ]
