# Generated by Django 4.2.7 on 2023-12-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0005_alter_comment_algorithm_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
