# Generated by Django 4.2.7 on 2023-12-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0006_alter_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_published',
        ),
    ]
