# Generated by Django 4.2.7 on 2023-12-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0007_remove_comment_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealgorithm',
            name='alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='imagealgorithm',
            name='caption',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
