# Generated by Django 4.2.7 on 2023-12-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0008_imagealgorithm_alt_imagealgorithm_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTaskAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm.algorithm')),
            ],
            options={
                'verbose_name': 'ссылка на задачу для алгоритма',
                'verbose_name_plural': 'ссылки на задачу для алгоритмов',
            },
        ),
    ]
