# Generated by Django 4.2.7 on 2024-01-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0010_alter_algorithm_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algorithms', to='algorithm.category'),
        ),
    ]
