# Generated by Django 4.2.7 on 2024-01-25 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0011_alter_algorithm_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealgorithm',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_algorithm', to='algorithm.algorithm'),
        ),
        migrations.AlterField(
            model_name='taskalgorithm',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_to_algorithm', to='algorithm.algorithm'),
        ),
        migrations.AlterField(
            model_name='urlalgorithm',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_to_theory_algorithm', to='algorithm.algorithm'),
        ),
        migrations.AlterField(
            model_name='urltaskalgorithm',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_to_online_tasks', to='algorithm.algorithm'),
        ),
    ]
